on:
  rss:
    url: http://feeds.feedburner.com/Acor3-SantoDelGiorno
jobs:
  beam:
    name: Beam to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send a Telegram message
        uses: appleboy/telegram-action@master
        with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |         
           Oggi si bestemmia: Dio (finché Aurelio non usa Gippy)
         format: html
