on:
  poll:
    url: https://the-forgotten-sannio-glug-bot.fly.dev/santo
    config:
      limit: 5
jobs:
  beam:
    name: Beam to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send a Telegram message
        env:
          nome_santo: ${{ on.poll.outputs.nome_santo }}
        uses: appleboy/telegram-action@master
        with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |         
           Oggi si bestemmia: ${{ nome_santo }}
         format: html
