on:
  poll:
    url: https://the-forgotten-sannio-glug-bot.fly.dev/santo
    config:
      limit: 5
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          santo: ${{ on.poll.outputs.nome_santo }}
  beam:
    name: Beam to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send a Telegram message
        uses: appleboy/telegram-action@master
        with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: |         
           Oggi si bestemmia: $santo
         format: html
